### ISSUE TITLE
Buggy Entities

### ISSUE THREAD

**Issue by guidingarrow** [DrkMatr1984/Piggyback#1] opened 2016-05-28 19:17 UTC
The following issues are caused when carrying certain entities using this plugin.

Allows User to fly by attempting to sit in/on:
Boat (All types)
Minecart

Prevents user from performing other actions:
Storage Minecart
Powered Minecart
Minecart with TNT (Also explodes when thrown)
Minecart with Hopper
Ender Crystal (Explodes when hit)
Anvil (all types)

Interferes with normal function:
Horse

Prevents the user from being hit by other players:
Sand (All types)
Gravel
Falling blocks in general.
Note that it only prevents them from being hit if someone aims for their head. Anywhere else they still take damage. 

Mobs/blocks that should probably be blocked:
Giant Zombie (Not a big deal, shouldn't ever see one)
Ender Dragon
Wither
Shulker
Ghast (Large, completely blocks view, could be worked around)
Slime (Large, completely block view, could be worked around)
Primed TNT

All hostile mobs, villagers, and squids take damage if the player tries to hit anything.
All players take damage if the player carrying them tries to hit anything.
All friendly mobs take damage if the player tries to hit anything while sneaking.
This happens regardless of the direction the player is looking.

Entity ID List: 
Primed TNT (PrimedTnt) 20,
Falling Block (FallingSand) 21,
Minecart with Command Block (MinecartCommandBlock) 40,
Boat (Boat) 41,
Minecart (MinecartRideable) 42,
Storage Minecart (MinecartChest) 43,
Powered Minecart (MinecartFurnace) 44,
Minecart with TNT (MinecartTNT) 45,
Minecart with Hopper (MinecartHopper) 46,
Minecart with Spawner (MinecartSpawner) 47,
Giant Zombie (Giant) 53,
Slime (Slime) 55,
Ghast (Ghast) 56,
Ender Dragon (EnderDragon) 63,
Wither (WitherBoss) 64,
Shulker (Shulker) 69,
Squid (Squid) 94.
Villager (Villager) 120,
Ender Crystal (EnderCrystal) 200,
Hostile Mobs 50 to 69,
Friendly Mobs 90 to 101.
Obtained from here: http://minecraft-ids.grahamedgecombe.com/entities

Let me know if you need any additional detail.

**Comment by DrkMatr1984** [comment] 2016-08-08 22:01
> All friendly mobs take damage if the player tries to hit anything while sneaking.

Do you mean sneaking and attacking bypasses pvp protections when this plugin is enabled? Because you can normally sneak and punch friendly mobs while sneaking unless there's something preventing that.

**Comment by DrkMatr1984** [comment] 2016-08-08 22:01
Btw, I am addressing as many of these issues as possible currently.

**Comment by guidingarrow** [comment] 2016-08-08 22:39
If I remember correctly I meant that when carrying a friendly mob they would take damage if you were sneaking and tried to attack something else. Whereas if you were to try to attack something else while not sneaking the carried mob does not take damage.

I'll try and confirm this after work if you don't have it figured out by then.

**Comment by DrkMatr1984** [comment] 2016-08-08 23:07
ok, thanks. Yeah I have to work in an hour, so probably not gonna mess with it anymore tonight. But I wanted to start the ball rolling and get the fixes done :)

**Comment by DrkMatr1984** [comment] 2016-10-24 17:13
Yup, you were right. I'm trying to look into that currently. I fixed the text bug and added some blacklists. I also noticed a few more potential bugs when browsing the code and fixed those. The flying with boats is caused by an exception in MC itself due to a circular riding error. (ie. you're riding the boat while the boat is riding you) I've been trying to solve the root cause of this as it happens when carrying any vehicle in 1.9+ with my plugin. There's also a few more features being added. Check out the issue logs.

**Comment by DrkMatr1984** [comment] 2017-10-11 20:21
Still solving some of these issues.  Working on cleaning up the code and solving as many as possible.

**Comment by DrkMatr1984** [comment] 2017-10-12 07:07
Allows User to fly by attempting to sit in/on:
~~Boat (All types)~~
~~Minecart~~

Prevents user from performing other actions:
~~Storage Minecart~~
~~Powered Minecart~~
~~Minecart with TNT (Also explodes when thrown)~~
~~Minecart with Hopper~~
~~Ender Crystal (Explodes when hit)~~
~~Anvil (all types)~~

Interferes with normal function:
Horse

Prevents the user from being hit by other players:
~~Sand (All types)~~
~~Gravel~~
~~Falling blocks in general.~~
Note that it only prevents them from being hit if someone aims for their head. Anywhere else they still take damage.

Mobs/blocks that should probably be blocked:
Giant Zombie (Not a big deal, shouldn't ever see one)
Ender Dragon
Wither
Shulker
Ghast (Large, completely blocks view, could be worked around)
Slime (Large, completely block view, could be worked around)
~~Primed TNT~~

~~All hostile mobs, villagers, and squids take damage if the player tries to hit anything.~~
~~All players take damage if the player carrying them tries to hit anything.~~
~~All friendly mobs take damage if the player tries to hit anything while sneaking.~~
~~This happens regardless of the direction the player is looking.~~

Entity ID List:
~~Primed TNT (PrimedTnt) 20,~~
~~Falling Block (FallingSand) 21,~~
~~Minecart with Command Block (MinecartCommandBlock) 40,~~
~~Boat (Boat) 41,~~
~~Minecart (MinecartRideable) 42,~~
~~Storage Minecart (MinecartChest) 43,~~
~~Powered Minecart (MinecartFurnace) 44,~~
~~Minecart with TNT (MinecartTNT) 45,~~
~~Minecart with Hopper (MinecartHopper) 46,~~
~~Minecart with Spawner (MinecartSpawner) 47,~~
Giant Zombie (Giant) 53,
Slime (Slime) 55,
Ghast (Ghast) 56,
Ender Dragon (EnderDragon) 63,
Wither (WitherBoss) 64,
Shulker (Shulker) 69,
Squid (Squid) 94.
Villager (Villager) 120,
~~Ender Crystal (EnderCrystal) 200,~~
Hostile Mobs 50 to 69,
Friendly Mobs 90 to 101.
Obtained from here: http://minecraft-ids.grahamedgecombe.com/entities

Let me know if you need any additional detail.

**Comment by DrkMatr1984** [comment] 2017-10-13 06:04
Making a dent. Fixed most of these simply by limiting entities allowed to be picked up to LivingEntities only. I will probably allow all mobs, as it's kind of the intent of the plugin. I added a blacklist to the config though which should allow users to block some of the LivingEntities they don't want to be picked up from being picked up.

**Comment by DrkMatr1984** [comment] 2018-02-19 04:38
Most of these errors fixed in 2.0, closing this issue.

**Closed as completed by DrkMatr1984** 2018-02-19 04:38 UTC
Labels: bug
